### ISSUE TITLE
macOS: Builds fine, but does not start

### ISSUE THREAD

**Issue by teutat3s** [totaljs/nosqlviewerapp#2]
Hello, 

thanks for this nice App!

On macOS High Sierra, build completes fine, but when running the app I get: 
Javascipt Error - Exception unable to find a valid app 
at Object ... nosqlviewerapp.app/Contentts/Resources/electron.asar/browser/init.js

to reproduce:
on macOS 10.13.6

`git clone https://github.com/totaljs/nosqlviewerapp`
`cd nosqlviewerapp`
`npm install`
`yarn pull`
`yarn build:mac`

run App.
Error.

It seems to be an issue for electron when source code and package.json are not in the same folder.
See https://github.com/electron-userland/electron-packager/issues/269
and https://github.com/costlocker/desktop/commit/825317fad446b09ab018bcd64e04c783ccbf0b0f

I then tried
`cp -r nosqlviewer/* .`
`yarn build:clean`
`yarn build:mac`

(with path adjusted in package.json: 
`"build:mac": "rm -fr nosqlviewerapp-darwin* && electron-packager ./ --platform=darwin",`

and this time it worked. :+1:

**Comment by petersirka** [comment]
Hi @Teutone, can you create a pull request with this fix? Thank you!

**Comment by petersirka** [comment]
Thank you!
